// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4mDhgvIQr93SvwaIyTUFMh-1FOkih734',
    appId: '1:664997133986:web:9e8c8751db2e64723fe1fb',
    messagingSenderId: '664997133986',
    projectId: 'spotty-616a0',
    authDomain: 'spotty-616a0.firebaseapp.com',
    storageBucket: 'spotty-616a0.firebasestorage.app',
    measurementId: 'G-4E8MBMCHLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cnZJmDKZcHpddUeQ61iklM_C7omlWsQ',
    appId: '1:664997133986:android:e1770d358960e18f3fe1fb',
    messagingSenderId: '664997133986',
    projectId: 'spotty-616a0',
    storageBucket: 'spotty-616a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi9PtrjFipTTsNoz1q4eFejyDR73wN6fY',
    appId: '1:664997133986:ios:2a3143ce52d533183fe1fb',
    messagingSenderId: '664997133986',
    projectId: 'spotty-616a0',
    storageBucket: 'spotty-616a0.firebasestorage.app',
    iosBundleId: 'com.example.mapFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi9PtrjFipTTsNoz1q4eFejyDR73wN6fY',
    appId: '1:664997133986:ios:2a3143ce52d533183fe1fb',
    messagingSenderId: '664997133986',
    projectId: 'spotty-616a0',
    storageBucket: 'spotty-616a0.firebasestorage.app',
    iosBundleId: 'com.example.mapFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4mDhgvIQr93SvwaIyTUFMh-1FOkih734',
    appId: '1:664997133986:web:5207bd597c6a5fe93fe1fb',
    messagingSenderId: '664997133986',
    projectId: 'spotty-616a0',
    authDomain: 'spotty-616a0.firebaseapp.com',
    storageBucket: 'spotty-616a0.firebasestorage.app',
    measurementId: 'G-ZXJW99MJCH',
  );

}